version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:

  #
  # DB
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=capitolzen

  #
  # Cache
  redis:
    image: redis:latest
    ports:
      - "6379"

  #
  # App
  django:
    restart: on-failure
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    env_file:
      - .env
    command: ["./utilities/wait-for-it.sh -t 90", "postgres:5432", "--", "/start-dev.sh"]
    depends_on:
      - postgres
      - mailhog
    environment:
      - POSTGRES_USER=capitolzen
      - POSTGRES_PASSWROD=capitolzen
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis

  #
  # Local Development utility for running commands.
  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=capitolzen
      - POSTGRES_PASSWORD=capitolzen
    volumes:
      - .:/app
    links:
      - postgres
      - redis

  #
  # Workers
  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    env_file: .env
    environment:
      - POSTGRES_USER=capitolzen
      - POSTGRES_PASSWORD=capitolzen
    depends_on:
     - postgres
     - redis
    links:
      - postgres
      - redis
    command: ["./utilities/wait-for-it.sh -t 90", "postgres:5432", "--", celery, -A, capitolzen.tasks, worker, --workdir=/app, --concurrency=4,  -l, INFO]
    volumes:
      - .:/app

  #
  # Beat
  celerybeat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    env_file: .env
    environment:
      - POSTGRES_USER=capitolzen
      - POSTGRES_PASSWORD=capitolzen
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    command: ["./utilities/wait-for-it.sh -t 90", "postgres:5432", "--", celery, -A, capitolzen.tasks, beat, --workdir=/app, -l, INFO]
    volumes:
      - .:/app

  #
  # Intercepts mail sent and provides a nice UI for debugging.
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8024:8024"

