version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=downdraft

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - mailhog
    environment:
      - POSTGRES_USER=downdraft
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"


  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=downdraft
    volumes:
      - .:/app

  #
  # Local Development utility for running commands.
  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=downdraft
      - POSTGRES_PASSWORD=downdraft
    volumes:
      - .:/app
    links:
      - postgres
      - redis

  #
  # Cache
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  #
  # Workers
  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    env_file: .env
    environment:
      - POSTGRES_USER=downdraft
      - POSTGRES_PASSWORD=downdraft
    depends_on:
     - postgres
     - redis
    links:
      - postgres
      - redis
    command: ["./utilities/wait-for-it.sh -t 90", "postgres:5432", "--", celery, -A, downdraft.tasks, worker, --workdir=/app, --concurrency=4,  -l, INFO]
    volumes:
      - .:/app

  #
  # Beat
  celerybeat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    env_file: .env
    environment:
      - POSTGRES_USER=downdraft
      - POSTGRES_PASSWORD=downdraft
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    command: ["./utilities/wait-for-it.sh -t 90", "postgres:5432", "--", celery, -A, downdraft.tasks, beat, --workdir=/app, -l, INFO]
    volumes:
      - .:/app

  #
  # Intercepts mail sent and provides a nice UI for debugging.

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

