version: '2'

services:
  django:
    build: ./compose/django/Dockerfile
    command: /gunicorn.sh
    env_file: .env
    container_name: django
    ports:
      - 5000

  nginx:
    build: ./compose/nginx
    links:
      - django
    depends_on:
      - django
    ports:
      - 443:443
    container_name: nginx

  celeryworker:
    user: django
    build: ./compose/django/Dockerfile
    env_file: .env
    command: [celery, -A, capitolzen.tasks, worker, --workdir=/app, --concurrency=4,  -l, INFO]

  celerybeat:
    user: django
    build: ./compose/django/Dockerfile
    env_file: .env
    command: [celery, -A, capitolzen.tasks, beat, --workdir=/app, -l, INFO]
