#!/bin/bash

#
# For whatever reason between the mix of docker-machine and circlci it's tough to get exit codes on these tests to
# return correctly so we have to do this instead of running it directly in the circle script so that we can ensure
# when tests pass or fail it actually returns the correct script exit codes.

set -o nounset
set -o errexit

#
# Have to call all the validation within a single docker-compose command so that
# we have access to the data generated by tests to submit to code analyzers.
# If we call our validation commands with individual docker-compose commands
# it results in a new container being created without files from the previous
# one.
# docker-compose -f dev.yml run pycharm sh /app/utilities/validator.sh
docker-compose -f dev.yml run pycharm sh /app/utilities/tests.sh
