version: 2
jobs:
  build:
    working_directory: ~/app
    executorType: machine
    steps:
      - checkout

      - run:
          name: Show Docker Versions
          command: |
            set -x
            docker --version
            docker-compose --version

      ##
      # NPM
      ##
      - restore_cache:
          key: dependency-cache-nltk
      - run:
          name: Pull NLTK Data
          command: |
            pip install nltk && python -m nltk.downloader -d ~/app/nltk_data all
      - save_cache:
          key: dependency-cache-nltk
          paths:
              - ~/app/nltk_data

      - run:
          name: Setup Environment
          command: |
            env > ~/app/.env

      - run:
          name: Build Docker Application
          command: |
            set -x
            docker-compose build

      - run:
          name: Increase VM Max Map Count
          command: |
            sudo sysctl -w vm.max_map_count=262144

      - run:
          name: Run Tests
          command: |
            set -ou pipefail
            docker-compose run pycharm sh /app/utilities/circletestrunner.sh
