# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 03:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20170624_1805'),
        ('organizations', '0005_organization_billing_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='is_read',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
