# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='meta',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='meta',
            new_name='metadata',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
