# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 11:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170816_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='references',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
