# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170703_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
