# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 09:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('references', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alert',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='group',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alerts',
        ),
    ]
