# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170923_2242'),
        ('users', '0004_user_avatar'),
    ]

    operations = [
    ]
