# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 14:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170809_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
