# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 14:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0036_bill_cosponsors_dups2'),
        ('users', '0007_auto_20171107_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('state', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('snoozed', 'Snoozed'), ('flagged', 'Flagged')], db_index=True, max_length=225)),
                ('title', models.CharField(choices=[('bill:introduced', 'Bill Introduced'), ('bill:updated', 'Bill Updated'), ('organization:user-add', 'User Joined'), ('organization:user-invite', 'User Invited'), ('organization:mention', 'Mentioned')], db_index=True, max_length=225)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.Bill')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.Committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'action',
                'verbose_name_plural': 'actions',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
