# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0036_bill_cosponsors_dups2'),
        ('users', '0008_auto_20171118_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='wrapper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.Wrapper'),
        ),
        migrations.AlterField(
            model_name='action',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.Committee'),
        ),
        migrations.AlterField(
            model_name='action',
            name='title',
            field=models.CharField(choices=[('bill:introduced', 'Bill Introduced'), ('wrapper:updated', 'Bill Updated'), ('organization:user-add', 'User Joined'), ('organization:user-invite', 'User Invited'), ('organization:mention', 'Mentioned')], db_index=True, max_length=225),
        ),
    ]
