# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170813_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='meta',
            new_name='metadata',
        ),
    ]
