# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20171119_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='action',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('snoozed', 'Snoozed'), ('flagged', 'Flagged')], db_index=True, default='active', max_length=225),
        ),
    ]
