# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 18:46
from __future__ import unicode_literals

import capitolzen.users.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20171206_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='preferences',
            new_name='features',
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=capitolzen.users.models.default_notifications),
        ),
    ]
