# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:43
from __future__ import unicode_literals

from django.db import migrations
from capitolzen.users.models import default_notifications


def forwards(apps, schema_editor):
    User = apps.get_model('users', 'User')
    defaults = default_notifications()
    for user in User.objects.all():
        user.notification_preferences = defaults
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180103_1346'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
