# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_props'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='title',
            field=models.CharField(choices=[('bill:introduced', 'Bill Introduced'), ('wrapper:updated', 'Bill Updated'), ('wrapper:committee_scheduled', 'Saved Bill in Committee'), ('organization:user-add', 'User Joined'), ('organization:user-invite', 'User Invited'), ('user:mention', 'Mentioned'), ('committee:meeting', 'Committee Meeting')], db_index=True, max_length=225),
        ),
    ]
