# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    Action = apps.get_model('users', 'Action')

    for action in Action.objects.all().iterator():
        fk = action.object_id
        content = action.content_type

        if content == 'bill':
            action.bill_id = fk
        elif content == 'wrapper':
            action.wrapper_id = fk
        elif content == 'event':
            action.event_id = fk
        else:
            raise Exception
        action.save()

class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0044_auto_20180206_1138'),
        ('users', '0015_auto_20180206_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.Bill'),
        ),
        migrations.AddField(
            model_name='action',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.Event'),
        ),
        migrations.AddField(
            model_name='action',
            name='wrapper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.Wrapper'),
        ),
        migrations.RunPython(forwards),
    ]
