# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20170624_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='publish_output',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='Generated Report', max_length=255),
        ),
    ]
