# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20170702_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='bills',
            new_name='wrappers',
        ),
        migrations.AddField(
            model_name='group',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
