# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20170707_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='wrappers',
            new_name='filter',
        ),
    ]
