# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_auto_20170722_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='update_frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
