# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 17:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_group_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='attachments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
