# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_report_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='meta',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='meta',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='meta',
            new_name='metadata',
        ),
    ]
