# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 13:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_report_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='static_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
