# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_report_static'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='modified',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='modified',
            field=models.DateTimeField(db_index=True),
        ),
    ]
