# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_auto_20170923_2242'),
        ('groups', '0015_report_static_list'),
    ]

    operations = [
    ]
