# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_auto_20171012_1950'),
        ('groups', '0017_auto_20171001_1957'),
    ]

    operations = [
    ]
