# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_auto_20171118_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_label',
            field=models.CharField(default='Client', max_length=255),
        ),
    ]
