# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0024_group_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user_list',
        ),
    ]
