# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0026_auto_20180206_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='attachments',
        ),
    ]
