# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0029_auto_20180222_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='recurring',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='template',
        ),
        migrations.AddField(
            model_name='report',
            name='display_type',
            field=models.CharField(choices=[('scorecard', 'scorecard'), ('table', 'table'), ('list', 'list'), ('slideshow', 'slideshow')], default='list', max_length=255),
        ),
        migrations.AlterField(
            model_name='reportlink',
            name='visibility',
            field=models.CharField(choices=[('unlimited', 'Anyone with link'), ('organization', 'Anyone in my org'), ('contacts', 'in list of emails'), ('once', 'just once')], db_index=True, default='organization', max_length=255),
        ),
    ]
