# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 21:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0030_auto_20180301_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlink',
            name='contact_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='reportlink',
            name='visibility',
            field=models.CharField(choices=[('anyone', 'Anyone with link'), ('organization', 'Anyone in my org'), ('contacts', 'in list of emails'), ('once', 'just once')], db_index=True, default='organization', max_length=255),
        ),
    ]
