# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 18:16
from __future__ import unicode_literals

import capitolzen.groups.mixins
import capitolzen.groups.models
import capitolzen.organizations.mixins
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hashid_field.field
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_organizationuser_is_guest'),
        ('proposals', '0044_auto_20180206_1138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0031_auto_20180301_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('scraped_data', django.contrib.postgres.fields.jsonb.JSONField(default=capitolzen.groups.models.generate_preview)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
            },
            bases=(models.Model, capitolzen.organizations.mixins.MixinResourcedOwnedByOrganization),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('anyone', 'Anyone with link'), ('organization', 'Anyone in my org')], db_index=True, default='organization', max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
            },
            bases=(models.Model, capitolzen.organizations.mixins.MixinResourcedOwnedByOrganization),
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('title', models.TextField(max_length=255)),
                ('status', models.TextField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=255)),
                ('files', models.ManyToManyField(blank=True, null=True, to='groups.File')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('links', models.ManyToManyField(blank=True, null=True, to='groups.Link')),
                ('reports', models.ManyToManyField(blank=True, null=True, to='groups.Report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wrappers', models.ManyToManyField(blank=True, null=True, to='proposals.Wrapper')),
            ],
            options={
                'verbose_name': 'update',
                'verbose_name_plural': 'updates',
            },
            bases=(models.Model, capitolzen.organizations.mixins.MixinResourcedOwnedByOrganization, capitolzen.groups.mixins.MixinResourceOwnedByPage),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reportlink',
            name='contact_list',
        ),
        migrations.RemoveField(
            model_name='reportlink',
            name='group',
        ),
        migrations.RemoveField(
            model_name='reportlink',
            name='visibility',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='report',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Page'),
        ),
    ]
