# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0032_auto_20180305_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportlink',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='reportlink',
            name='report',
        ),
        migrations.AddField(
            model_name='page',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='My Group Page', max_length=255),
        ),
        migrations.DeleteModel(
            name='ReportLink',
        ),
    ]
