# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-06 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0034_auto_20180306_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='groups.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='update',
            name='page',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='update', to='groups.Page'),
            preserve_default=False,
        ),
    ]
