# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-06 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_organizationuser_is_guest'),
        ('groups', '0035_auto_20180306_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
            preserve_default=False,
        ),
    ]
