# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-08 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0037_file_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='guest_users',
            field=models.ManyToManyField(related_name='guest_users_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_to_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
