# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-30 08:38
from __future__ import unicode_literals

import capitolzen.groups.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0038_auto_20180308_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='avatar',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=capitolzen.groups.models.avatar_directory_path),
        ),
        migrations.AddField(
            model_name='page',
            name='bill_layout',
            field=models.CharField(choices=[('table', 'Table'), ('slides', 'slides'), ('list', 'list')], default='table', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='viewers',
            field=models.ManyToManyField(related_name='page_viewer_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='update',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='groups.Group'),
        ),
    ]
