# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-30 08:46
from __future__ import unicode_literals

import capitolzen.groups.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0039_auto_20180430_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='structured_page_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=capitolzen.groups.models.create_structured_page_info),
        ),
    ]
