# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 07:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20170529_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contacts',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='demographic_org_type',
            field=models.CharField(blank=True, choices=[('association', 'Association'), ('union', 'Labor Union'), ('multi_client', 'Multi Client'), ('corporate', 'Corporation'), ('individual', 'Individual')], max_length=255),
        ),
    ]
