# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20170613_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='billing_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
