# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_billing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
