# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organizationinvite_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='meta',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='organizationinvite',
            old_name='meta',
            new_name='metadata',
        ),
    ]
