# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organizationinvite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
