# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20170813_1305'),
        ('organizations', '0008_auto_20170816_0609'),
    ]

    operations = [
    ]
