# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_merge_20170816_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvite',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='modified',
            field=models.DateTimeField(db_index=True),
        ),
    ]
