# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_merge_20170816_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
