# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 19:32
from __future__ import unicode_literals

import capitolzen.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_organization_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='avatar',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=capitolzen.organizations.models.avatar_directory_path),
        ),
    ]
