# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_merge_20171017_0859'),
        ('organizations', '0013_file'),
    ]

    operations = [
    ]
