# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_merge_20171017_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(db_index=True),
        ),
    ]
