# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 11:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_auto_20171021_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='available_states',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=['MI'], size=None),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='modified',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
