# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_auto_20171102_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
