# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_auto_20171107_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='chargebee_customer_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
