# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 05:21
from __future__ import unicode_literals

from django.db import migrations
from capitolzen.organizations.services import ChargebeeOrganizationSync


def forwards(apps, schema_editor):

    Organization = apps.get_model('organizations', 'Organization')

    for organization in Organization.objects.all().iterator():
        if not organization.chargebee_customer_id:
            ChargebeeOrganizationSync().execute(organization, 'create_or_update')


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_organization_chargebee_customer_id'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
