# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_organization_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='client_label',
            field=models.CharField(default='Client', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='client_label_plural',
            field=models.CharField(default='Clients', max_length=255),
        ),
    ]
