# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 06:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_auto_20170613_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('state', models.TextField(choices=[('MI', 'Michigan'), ('OH', 'Ohio')])),
                ('status', models.TextField()),
                ('committee', models.TextField()),
                ('sponsor', models.TextField()),
                ('title', models.TextField()),
                ('state_id', models.CharField(max_length=225)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=225), default=list, size=None)),
                ('history', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True))
            ],
            options={
                'verbose_name': 'bill',
                'verbose_name_plural': 'bill',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wrapper',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('groups', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('notes', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.Bill')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
            options={
                'verbose_name': 'wrapper',
                'verbose_name_plural': 'wrapper',
                'abstract': False,
            },
        ),
    ]
