# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20170624_1805'),
        ('proposals', '0005_auto_20170628_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrapper',
            name='groups',
        ),
        migrations.AddField(
            model_name='wrapper',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
        migrations.AddField(
            model_name='wrapper',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
