# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 10:13
from __future__ import unicode_literals
import pytz
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_wrapper_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='affected_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='last_action_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 6, 13, 34, 515806, pytz.UTC)),
        ),
        migrations.AddField(
            model_name='bill',
            name='remote_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
