# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 00:34
from __future__ import unicode_literals
import pytz
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_auto_20170716_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapper',
            name='position_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='last_action_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 20, 34, 54, 613330, pytz.UTC)),
        ),
    ]
