# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 19:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_auto_20170720_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='last_action_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 22, 15, 17, 36, 941505)),
        ),
    ]
