# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 19:36
from __future__ import unicode_literals
import pytz
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_auto_20170722_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='last_action_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 22, 15, 36, 5, 618140, pytz.UTC)),
        ),
    ]
