# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_auto_20170722_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='last_action_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 23, 4, 42, 39, 927784)),
        ),
    ]
