# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 15:41
from __future__ import unicode_literals

import capitolzen.proposals.mixins
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_auto_20170723_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('chamber', models.CharField(max_length=255)),
                ('remote_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'abstract': False,
            },
            bases=(models.Model, capitolzen.proposals.mixins.MixinExternalData),
        ),
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('remote_id', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('chamber', models.CharField(max_length=255)),
                ('party', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('url', models.URLField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('suffixes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'legislator',
                'verbose_name_plural': 'legislators',
                'abstract': False,
            },
            bases=(models.Model, capitolzen.proposals.mixins.MixinExternalData),
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'bill', 'verbose_name_plural': 'bills'},
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='versions',
            new_name='cosponsors',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='affected_section',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='last_action_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='remote_url',
        ),
        migrations.AddField(
            model_name='bill',
            name='action_dates',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='chamber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='companions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='bill',
            name='documents',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bill',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='session',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='sources',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bill',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='votes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bill',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='bill',
            name='current_committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.Committee'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.Legislator'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='state_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
