# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_auto_20170728_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='subcommittee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
