# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 09:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0018_committee_subcommittee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cosponsors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.Legislator'),
        ),
    ]
