# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 13:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0019_auto_20170729_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cosponsors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='state',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
