# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 14:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0020_auto_20170802_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_versions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
