# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 02:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0022_auto_20170813_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='current_version',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='sponsors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bill',
            name='modified',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='committee',
            name='modified',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='modified',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='wrapper',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wrapper',
            name='modified',
            field=models.DateTimeField(db_index=True),
        ),
    ]
