# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 01:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0024_auto_20171001_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, max_length=255, null=True),
        ),
    ]
