# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0024_auto_20171001_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='remote_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
