# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0026_auto_20171017_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='legislator',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='legislator',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
