# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0027_auto_20171021_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='content_metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='remote_id',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
