# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0028_auto_20171021_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='modified',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='committee',
            name='modified',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='modified',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wrapper',
            name='modified',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
