# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 01:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0030_remove_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_raw_text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_text_analysis',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
