# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0031_auto_20171103_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapper',
            name='files',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
