# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0032_wrapper_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrapper',
            name='notes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
