# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:43
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    Bill = apps.get_model('proposals', 'Bill')
    Committee = apps.get_model('proposals', 'Committee')

    for bill in Bill.objects.all().iterator():
        if getattr(bill, 'history', False):
            for action in bill.history:
                committee = None
                chamber = None
                if action['type'][0] == 'committee:referred':
                    action_parts = action['action'].lower().split('referred to committee on ')
                    if len(action_parts) > 1:
                        committee = action_parts[1]
                        chamber = action['actor']
                if action['type'][0] == 'committee:passed':
                    committee = None
                    chamber = None

                if committee and chamber:
                    bill.current_committee = Committee.objects.filter(name__icontains=committee, chamber=chamber).first()
                    bill.save()


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0033_auto_20171108_1043'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
