# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 09:09
from __future__ import unicode_literals

import capitolzen.proposals.mixins
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0036_bill_cosponsors_dups2'),
    ]

    def forwards(apps, schema_editor):
        Bill = apps.get_model('proposals', 'Bill')

        for bill in Bill.objects.all().iterator():
            if bill.cosponsors:
                cosponsors = bill.cosponsors
                cosponsors = set(cosponsors)
                bill.cosponsors = list(cosponsors)
                bill.save()

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
                ('chamber', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('event_type', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('remote_id', models.TextField(blank=True, max_length=255, null=True)),
                ('location_text', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('attachments', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.Committee')),
                ('legislator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.Legislator')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'Events',
                'abstract': False,
            },
            bases=(models.Model, capitolzen.proposals.mixins.MixinExternalData),
        ),
        migrations.RunPython(forwards),
    ]
