# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0037_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('committee:meeting', 'Committee - Meeting')], default='committee:meeting', max_length=255),
        ),
    ]
