# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 21:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0041_make_leg_remote_id_unique_20171224_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='related_bill_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), default=list, size=None),
        ),
    ]
