# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 09:09
from __future__ import unicode_literals

import capitolzen.proposals.mixins
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0042_bill_related_bill_ids'),
    ]

    def forwards(apps, schema_editor):
        Event = apps.get_model('proposals', 'Event')
        Bill = apps.get_model('proposals', 'Bill')

        for event in Event.objects.filter(attachments__has_key='billlist'):
            uuid_list = []
            blist = event.attachments.get('billlist')
            for b in blist:
                try:
                    bill = Bill.objects.get(state_id=b)
                    uuid_list.append(bill.id)
                    event.attachments['billlist'] = uuid_list
                    event.save()
                except Exception:
                    continue

    operations = [
        migrations.RunPython(forwards),
    ]
