# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0043_event_bill_list_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrapper',
            name='position',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('support', 'support'), ('oppose', 'oppose'), ('neutral', 'neutral')], default='none', max_length=255),
        ),
    ]
