# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 11:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='features',
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_address_one',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_address_two',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_city',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_payment_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256), default=list, size=None),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
