# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 04:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20170609_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='stripe_payment_methods',
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_payment_tokens',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='billing_address_one',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='billing_city',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='billing_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='billing_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='demographic_org_type',
            field=models.CharField(blank=True, choices=[('association', 'Association'), ('union', 'Labor Union'), ('multi_client', 'Multi Client'), ('corporate', 'Corporation'), ('individual', 'Individual')], default='individual', max_length=255),
        ),
    ]
